### ISSUE TITLE
Out of Memory

### ISSUE THREAD

**Issue by rvssatyaditya** [juancarlospaco/faster-than-requests#7]
it's throwing a message saying out of memory while importing.

**Comment by juancarlospaco** [comment]
Post the source code that you are using, with OS, versions, etc.

**Comment by junhoyeo** [comment]
I'm using Python 3.7.3 with macOS High Sierra 10.13.3.

```
$ pip3 install faster_than_requests
ollecting faster_than_requests
  Downloading https://files.pythonhosted.org/packages/71/dd/b2160ca61114a35238bf9d5f5ccb88ca759b6d2f9246e6e13f4d263c270d/faster_than_requests-0.1.zip (249kB)
    100% |████████████████████████████████| 256kB 1.8MB/s 
Building wheels for collected packages: faster-than-requests
  Building wheel for faster-than-requests (setup.py) ... error
  Complete output from command /usr/local/opt/python/bin/python3.7 -u -c "import setuptools, tokenize;__file__='/private/var/folders/db/l41fnkcn0kjfqph_t_4mj29c0000gn/T/pip-install-5gy84qli/faster-than-requests/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /private/var/folders/db/l41fnkcn0kjfqph_t_4mj29c0000gn/T/pip-wheel-kiubpi66 --python-tag cp37:
  running bdist_wheel
  running build
  running build_ext
  building 'faster_than_requests' extension
  creating build
  creating build/temp.macosx-10.13-x86_64-3.7
  clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/Tk.framework/Versions/8.5/Headers -I. -I/usr/local/include -I/usr/local/opt/openssl/include -I/usr/local/opt/sqlite/include -I/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/include/python3.7m -c stdlib_asyncstreams.c -o build/temp.macosx-10.13-x86_64-3.7/stdlib_asyncstreams.o -flto -ffast-math -march=native -O3
  clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/Tk.framework/Versions/8.5/Headers -I. -I/usr/local/include -I/usr/local/opt/openssl/include -I/usr/local/opt/sqlite/include -I/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/include/python3.7m -c stdlib_httpcore.c -o build/temp.macosx-10.13-x86_64-3.7/stdlib_httpcore.o -flto -ffast-math -march=native -O3
  stdlib_httpcore.c:299:2: warning: code will never be executed [-Wunreachable-code]
          goto LA1_;
          ^~~~~~~~~
  1 warning generated.
  clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/Tk.framework/Versions/8.5/Headers -I. -I/usr/local/include -I/usr/local/opt/openssl/include -I/usr/local/opt/sqlite/include -I/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/include/python3.7m -c stdlib_os.c -o build/temp.macosx-10.13-x86_64-3.7/stdlib_os.o -flto -ffast-math -march=native -O3
  clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/Tk.framework/Versions/8.5/Headers -I. -I/usr/local/include -I/usr/local/opt/openssl/include -I/usr/local/opt/sqlite/include -I/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/include/python3.7m -c stdlib_strscans.c -o build/temp.macosx-10.13-x86_64-3.7/stdlib_strscans.o -flto -ffast-math -march=native -O3
  clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/Tk.framework/Versions/8.5/Headers -I. -I/usr/local/include -I/usr/local/opt/openssl/include -I/usr/local/opt/sqlite/include -I/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/include/python3.7m -c stdlib_base64.c -o build/temp.macosx-10.13-x86_64-3.7/stdlib_base64.o -flto -ffast-math -march=native -O3
  clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/Tk.framework/Versions/8.5/Headers -I. -I/usr/local/include -I/usr/local/opt/openssl/include -I/usr/local/opt/sqlite/include -I/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/include/python3.7m -c stdlib_json.c -o build/temp.macosx-10.13-x86_64-3.7/stdlib_json.o -flto -ffast-math -march=native -O3
  stdlib_json.c:916:2: warning: code will never be executed [-Wunreachable-code]
          goto LA1_;
          ^~~~~~~~~
  1 warning generated.
  clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/Tk.framework/Versions/8.5/Headers -I. -I/usr/local/include -I/usr/local/opt/openssl/include -I/usr/local/opt/sqlite/include -I/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/include/python3.7m -c stdlib_ospaths.c -o build/temp.macosx-10.13-x86_64-3.7/stdlib_ospaths.o -flto -ffast-math -march=native -O3
  clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/Tk.framework/Versions/8.5/Headers -I. -I/usr/local/include -I/usr/local/opt/openssl/include -I/usr/local/opt/sqlite/include -I/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/include/python3.7m -c stdlib_strtabs.c -o build/temp.macosx-10.13-x86_64-3.7/stdlib_strtabs.o -flto -ffast-math -march=native -O3
  clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/Tk.framework/Versions/8.5/Headers -I. -I/usr/local/include -I/usr/local/opt/openssl/include -I/usr/local/opt/sqlite/include -I/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/include/python3.7m -c nimpy_nimpy.c -o build/temp.macosx-10.13-x86_64-3.7/nimpy_nimpy.o -flto -ffast-math -march=native -O3
  nimpy_nimpy.c:788:21: warning: comparison of integers of different signs: 'NI' (aka 'long long') and 'size_t' (aka 'unsigned long') [-Wsign-compare]
                  T5_ = (argsLenReq <= sz);
                         ~~~~~~~~~~ ^  ~~
  nimpy_nimpy.c:790:13: warning: comparison of integers of different signs: 'size_t' (aka 'unsigned long') and 'NI' (aka 'long long') [-Wsign-compare]
                  T5_ = (sz <= argsLen);
                         ~~ ^  ~~~~~~~
  nimpy_nimpy.c:797:16: warning: comparison of integers of different signs: 'size_t' (aka 'unsigned long') and 'NI' (aka 'long long') [-Wsign-compare]
                  result = (sz == argsLen);
                            ~~ ^  ~~~~~~~
  nimpy_nimpy.c:1104:16: warning: comparison of integers of different signs: 'NI' (aka 'long long') and 'size_t' (aka 'unsigned long') [-Wsign-compare]
                  if (!(argIdx < T3_)) goto LA4_;
                        ~~~~~~ ^ ~~~
  4 warnings generated.
  clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/Tk.framework/Versions/8.5/Headers -I. -I/usr/local/include -I/usr/local/opt/openssl/include -I/usr/local/opt/sqlite/include -I/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/include/python3.7m -c stdlib_bitops.c -o build/temp.macosx-10.13-x86_64-3.7/stdlib_bitops.o -flto -ffast-math -march=native -O3
  clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/Tk.framework/Versions/8.5/Headers -I. -I/usr/local/include -I/usr/local/opt/openssl/include -I/usr/local/opt/sqlite/include -I/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/include/python3.7m -c stdlib_lexbase.c -o build/temp.macosx-10.13-x86_64-3.7/stdlib_lexbase.o -flto -ffast-math -march=native -O3
  stdlib_lexbase.c:161:5: warning: code will never be executed [-Wunreachable-code]
                                  goto LA17_;
                                  ^~~~~~~~~~
  1 warning generated.
  clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/Tk.framework/Versions/8.5/Headers -I. -I/usr/local/include -I/usr/local/opt/openssl/include -I/usr/local/opt/sqlite/include -I/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/include/python3.7m -c stdlib_parsejson.c -o build/temp.macosx-10.13-x86_64-3.7/stdlib_parsejson.o -flto -ffast-math -march=native -O3
  clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/Tk.framework/Versions/8.5/Headers -I. -I/usr/local/include -I/usr/local/opt/openssl/include -I/usr/local/opt/sqlite/include -I/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/include/python3.7m -c stdlib_strutils.c -o build/temp.macosx-10.13-x86_64-3.7/stdlib_strutils.o -flto -ffast-math -march=native -O3
  stdlib_strutils.c:314:4: warning: code will never be executed [-Wunreachable-code]
                          goto LA25_;
                          ^~~~~~~~~~
  stdlib_strutils.c:307:4: warning: code will never be executed [-Wunreachable-code]
                          goto LA25_;
                          ^~~~~~~~~~
  2 warnings generated.
  clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/Tk.framework/Versions/8.5/Headers -I. -I/usr/local/include -I/usr/local/opt/openssl/include -I/usr/local/opt/sqlite/include -I/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/include/python3.7m -c nimpy_py_lib.c -o build/temp.macosx-10.13-x86_64-3.7/nimpy_py_lib.o -flto -ffast-math -march=native -O3
  clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/Tk.framework/Versions/8.5/Headers -I. -I/usr/local/include -I/usr/local/opt/openssl/include -I/usr/local/opt/sqlite/include -I/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/include/python3.7m -c stdlib_complex.c -o build/temp.macosx-10.13-x86_64-3.7/stdlib_complex.o -flto -ffast-math -march=native -O3
  clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/Tk.framework/Versions/8.5/Headers -I. -I/usr/local/include -I/usr/local/opt/openssl/include -I/usr/local/opt/sqlite/include -I/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/include/python3.7m -c stdlib_lists.c -o build/temp.macosx-10.13-x86_64-3.7/stdlib_lists.o -flto -ffast-math -march=native -O3
  clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/Tk.framework/Versions/8.5/Headers -I. -I/usr/local/include -I/usr/local/opt/openssl/include -I/usr/local/opt/sqlite/include -I/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/include/python3.7m -c stdlib_parseutils.c -o build/temp.macosx-10.13-x86_64-3.7/stdlib_parseutils.o -flto -ffast-math -march=native -O3
  clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/Tk.framework/Versions/8.5/Headers -I. -I/usr/local/include -I/usr/local/opt/openssl/include -I/usr/local/opt/sqlite/include -I/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/include/python3.7m -c stdlib_system.c -o build/temp.macosx-10.13-x86_64-3.7/stdlib_system.o -flto -ffast-math -march=native -O3
  stdlib_system.c:4474:2: warning: code will never be executed [-Wunreachable-code]
          goto LA1_;
          ^~~~~~~~~
  1 warning generated.
  clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/Tk.framework/Versions/8.5/Headers -I. -I/usr/local/include -I/usr/local/opt/openssl/include -I/usr/local/opt/sqlite/include -I/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/include/python3.7m -c nimpy_py_types.c -o build/temp.macosx-10.13-x86_64-3.7/nimpy_py_types.o -flto -ffast-math -march=native -O3
  clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/Tk.framework/Versions/8.5/Headers -I. -I/usr/local/include -I/usr/local/opt/openssl/include -I/usr/local/opt/sqlite/include -I/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/include/python3.7m -c stdlib_cstrutils.c -o build/temp.macosx-10.13-x86_64-3.7/stdlib_cstrutils.o -flto -ffast-math -march=native -O3
  clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/Tk.framework/Versions/8.5/Headers -I. -I/usr/local/include -I/usr/local/opt/openssl/include -I/usr/local/opt/sqlite/include -I/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/include/python3.7m -c stdlib_macros.c -o build/temp.macosx-10.13-x86_64-3.7/stdlib_macros.o -flto -ffast-math -march=native -O3
  clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/Tk.framework/Versions/8.5/Headers -I. -I/usr/local/include -I/usr/local/opt/openssl/include -I/usr/local/opt/sqlite/include -I/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/include/python3.7m -c stdlib_posix.c -o build/temp.macosx-10.13-x86_64-3.7/stdlib_posix.o -flto -ffast-math -march=native -O3
  clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/Tk.framework/Versions/8.5/Headers -I. -I/usr/local/include -I/usr/local/opt/openssl/include -I/usr/local/opt/sqlite/include -I/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/include/python3.7m -c stdlib_tables.c -o build/temp.macosx-10.13-x86_64-3.7/stdlib_tables.o -flto -ffast-math -march=native -O3
  clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/Tk.framework/Versions/8.5/Headers -I. -I/usr/local/include -I/usr/local/opt/openssl/include -I/usr/local/opt/sqlite/include -I/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/include/python3.7m -c nimpy_py_utils.c -o build/temp.macosx-10.13-x86_64-3.7/nimpy_py_utils.o -flto -ffast-math -march=native -O3
  clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/Tk.framework/Versions/8.5/Headers -I. -I/usr/local/include -I/usr/local/opt/openssl/include -I/usr/local/opt/sqlite/include -I/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/include/python3.7m -c stdlib_deques.c -o build/temp.macosx-10.13-x86_64-3.7/stdlib_deques.o -flto -ffast-math -march=native -O3
  clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/Tk.framework/Versions/8.5/Headers -I. -I/usr/local/include -I/usr/local/opt/openssl/include -I/usr/local/opt/sqlite/include -I/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/include/python3.7m -c stdlib_math.c -o build/temp.macosx-10.13-x86_64-3.7/stdlib_math.o -flto -ffast-math -march=native -O3
  clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/Tk.framework/Versions/8.5/Headers -I. -I/usr/local/include -I/usr/local/opt/openssl/include -I/usr/local/opt/sqlite/include -I/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/include/python3.7m -c stdlib_random.c -o build/temp.macosx-10.13-x86_64-3.7/stdlib_random.o -flto -ffast-math -march=native -O3
  clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/Tk.framework/Versions/8.5/Headers -I. -I/usr/local/include -I/usr/local/opt/openssl/include -I/usr/local/opt/sqlite/include -I/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/include/python3.7m -c stdlib_times.c -o build/temp.macosx-10.13-x86_64-3.7/stdlib_times.o -flto -ffast-math -march=native -O3
  clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/Tk.framework/Versions/8.5/Headers -I. -I/usr/local/include -I/usr/local/opt/openssl/include -I/usr/local/opt/sqlite/include -I/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/include/python3.7m -c stdlib_algorithm.c -o build/temp.macosx-10.13-x86_64-3.7/stdlib_algorithm.o -flto -ffast-math -march=native -O3
  clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/Tk.framework/Versions/8.5/Headers -I. -I/usr/local/include -I/usr/local/opt/openssl/include -I/usr/local/opt/sqlite/include -I/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/include/python3.7m -c stdlib_dynlib.c -o build/temp.macosx-10.13-x86_64-3.7/stdlib_dynlib.o -flto -ffast-math -march=native -O3
  clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/Tk.framework/Versions/8.5/Headers -I. -I/usr/local/include -I/usr/local/opt/openssl/include -I/usr/local/opt/sqlite/include -I/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/include/python3.7m -c stdlib_mimetypes.c -o build/temp.macosx-10.13-x86_64-3.7/stdlib_mimetypes.o -flto -ffast-math -march=native -O3
  clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/Tk.framework/Versions/8.5/Headers -I. -I/usr/local/include -I/usr/local/opt/openssl/include -I/usr/local/opt/sqlite/include -I/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/include/python3.7m -c stdlib_selectors.c -o build/temp.macosx-10.13-x86_64-3.7/stdlib_selectors.o -flto -ffast-math -march=native -O3
  clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/Tk.framework/Versions/8.5/Headers -I. -I/usr/local/include -I/usr/local/opt/openssl/include -I/usr/local/opt/sqlite/include -I/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/include/python3.7m -c stdlib_typetraits.c -o build/temp.macosx-10.13-x86_64-3.7/stdlib_typetraits.o -flto -ffast-math -march=native -O3
  clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/Tk.framework/Versions/8.5/Headers -I. -I/usr/local/include -I/usr/local/opt/openssl/include -I/usr/local/opt/sqlite/include -I/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/include/python3.7m -c stdlib_asyncdispatch.c -o build/temp.macosx-10.13-x86_64-3.7/stdlib_asyncdispatch.o -flto -ffast-math -march=native -O3
  clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/Tk.framework/Versions/8.5/Headers -I. -I/usr/local/include -I/usr/local/opt/openssl/include -I/usr/local/opt/sqlite/include -I/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/include/python3.7m -c stdlib_epoll.c -o build/temp.macosx-10.13-x86_64-3.7/stdlib_epoll.o -flto -ffast-math -march=native -O3
  clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/Tk.framework/Versions/8.5/Headers -I. -I/usr/local/include -I/usr/local/opt/openssl/include -I/usr/local/opt/sqlite/include -I/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/include/python3.7m -c stdlib_nativesockets.c -o build/temp.macosx-10.13-x86_64-3.7/stdlib_nativesockets.o -flto -ffast-math -march=native -O3
  clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/Tk.framework/Versions/8.5/Headers -I. -I/usr/local/include -I/usr/local/opt/openssl/include -I/usr/local/opt/sqlite/include -I/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/include/python3.7m -c stdlib_sequtils.c -o build/temp.macosx-10.13-x86_64-3.7/stdlib_sequtils.o -flto -ffast-math -march=native -O3
  clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/Tk.framework/Versions/8.5/Headers -I. -I/usr/local/include -I/usr/local/opt/openssl/include -I/usr/local/opt/sqlite/include -I/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/include/python3.7m -c stdlib_unicode.c -o build/temp.macosx-10.13-x86_64-3.7/stdlib_unicode.o -flto -ffast-math -march=native -O3
  clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/Tk.framework/Versions/8.5/Headers -I. -I/usr/local/include -I/usr/local/opt/openssl/include -I/usr/local/opt/sqlite/include -I/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/include/python3.7m -c stdlib_asyncfile.c -o build/temp.macosx-10.13-x86_64-3.7/stdlib_asyncfile.o -flto -ffast-math -march=native -O3
  clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/Tk.framework/Versions/8.5/Headers -I. -I/usr/local/include -I/usr/local/opt/openssl/include -I/usr/local/opt/sqlite/include -I/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/include/python3.7m -c stdlib_hashes.c -o build/temp.macosx-10.13-x86_64-3.7/stdlib_hashes.o -flto -ffast-math -march=native -O3
  clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/Tk.framework/Versions/8.5/Headers -I. -I/usr/local/include -I/usr/local/opt/openssl/include -I/usr/local/opt/sqlite/include -I/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/include/python3.7m -c stdlib_net.c -o build/temp.macosx-10.13-x86_64-3.7/stdlib_net.o -flto -ffast-math -march=native -O3
  stdlib_net.c:895:4: warning: code will never be executed [-Wunreachable-code]
                          goto LA55_;
                          ^~~~~~~~~~
  stdlib_net.c:784:5: warning: code will never be executed [-Wunreachable-code]
                                  goto LA17_;
                                  ^~~~~~~~~~
  stdlib_net.c:769:5: warning: code will never be executed [-Wunreachable-code]
                                  goto LA11_;
                                  ^~~~~~~~~~
  stdlib_net.c:1411:5: warning: code will never be executed [-Wunreachable-code]
                                  goto LA8_;
                                  ^~~~~~~~~
  stdlib_net.c:1792:2: warning: code will never be executed [-Wunreachable-code]
          goto LA5_;
          ^~~~~~~~~
  stdlib_net.c:1833:4: warning: code will never be executed [-Wunreachable-code]
                          popCurrentException();
                          ^~~~~~~~~~~~~~~~~~~
  stdlib_net.c:2203:7: warning: code will never be executed [-Wunreachable-code]
                                                  goto LA32_;
                                                  ^~~~~~~~~~
  stdlib_net.c:2175:5: warning: code will never be executed [-Wunreachable-code]
                                  goto LA17_;
                                  ^~~~~~~~~~
  stdlib_net.c:2172:21: warning: code will never be executed [-Wunreachable-code]
                                          result = ((NI) 0);
                                                         ^
  stdlib_net.c:2418:4: warning: code will never be executed [-Wunreachable-code]
                          goto LA16_;
                          ^~~~~~~~~~
  stdlib_net.c:2406:4: warning: code will never be executed [-Wunreachable-code]
                          goto LA16_;
                          ^~~~~~~~~~
  stdlib_net.c:2355:4: warning: code will never be executed [-Wunreachable-code]
                          goto LA4_;
                          ^~~~~~~~~
  12 warnings generated.
  clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/Tk.framework/Versions/8.5/Headers -I. -I/usr/local/include -I/usr/local/opt/openssl/include -I/usr/local/opt/sqlite/include -I/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/include/python3.7m -c stdlib_sets.c -o build/temp.macosx-10.13-x86_64-3.7/stdlib_sets.o -flto -ffast-math -march=native -O3
  clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/Tk.framework/Versions/8.5/Headers -I. -I/usr/local/include -I/usr/local/opt/openssl/include -I/usr/local/opt/sqlite/include -I/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/include/python3.7m -c stdlib_uri.c -o build/temp.macosx-10.13-x86_64-3.7/stdlib_uri.o -flto -ffast-math -march=native -O3
  clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/Tk.framework/Versions/8.5/Headers -I. -I/usr/local/include -I/usr/local/opt/openssl/include -I/usr/local/opt/sqlite/include -I/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/include/python3.7m -c stdlib_asyncfutures.c -o build/temp.macosx-10.13-x86_64-3.7/stdlib_asyncfutures.o -flto -ffast-math -march=native -O3
  clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/Tk.framework/Versions/8.5/Headers -I. -I/usr/local/include -I/usr/local/opt/openssl/include -I/usr/local/opt/sqlite/include -I/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/include/python3.7m -c stdlib_heapqueue.c -o build/temp.macosx-10.13-x86_64-3.7/stdlib_heapqueue.o -flto -ffast-math -march=native -O3
  clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/Tk.framework/Versions/8.5/Headers -I. -I/usr/local/include -I/usr/local/opt/openssl/include -I/usr/local/opt/sqlite/include -I/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/include/python3.7m -c stdlib_openssl.c -o build/temp.macosx-10.13-x86_64-3.7/stdlib_openssl.o -flto -ffast-math -march=native -O3
  clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/Tk.framework/Versions/8.5/Headers -I. -I/usr/local/include -I/usr/local/opt/openssl/include -I/usr/local/opt/sqlite/include -I/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/include/python3.7m -c stdlib_streams.c -o build/temp.macosx-10.13-x86_64-3.7/stdlib_streams.o -flto -ffast-math -march=native -O3
  clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/Tk.framework/Versions/8.5/Headers -I. -I/usr/local/include -I/usr/local/opt/openssl/include -I/usr/local/opt/sqlite/include -I/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/include/python3.7m -c stdlib_asyncnet.c -o build/temp.macosx-10.13-x86_64-3.7/stdlib_asyncnet.o -flto -ffast-math -march=native -O3
  clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/Tk.framework/Versions/8.5/Headers -I. -I/usr/local/include -I/usr/local/opt/openssl/include -I/usr/local/opt/sqlite/include -I/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/include/python3.7m -c stdlib_httpclient.c -o build/temp.macosx-10.13-x86_64-3.7/stdlib_httpclient.o -flto -ffast-math -march=native -O3
  clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/Tk.framework/Versions/8.5/Headers -I. -I/usr/local/include -I/usr/local/opt/openssl/include -I/usr/local/opt/sqlite/include -I/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/include/python3.7m -c stdlib_options.c -o build/temp.macosx-10.13-x86_64-3.7/stdlib_options.o -flto -ffast-math -march=native -O3
  clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/Tk.framework/Versions/8.5/Headers -I. -I/usr/local/include -I/usr/local/opt/openssl/include -I/usr/local/opt/sqlite/include -I/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/include/python3.7m -c stdlib_strformat.c -o build/temp.macosx-10.13-x86_64-3.7/stdlib_strformat.o -flto -ffast-math -march=native -O3
  clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/Tk.framework/Versions/8.5/Headers -I. -I/usr/local/include -I/usr/local/opt/openssl/include -I/usr/local/opt/sqlite/include -I/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/include/python3.7m -c faster_than_requests_faster_than_requests.c -o build/temp.macosx-10.13-x86_64-3.7/faster_than_requests_faster_than_requests.o -flto -ffast-math -march=native -O3
  creating build/lib.macosx-10.13-x86_64-3.7
  clang -bundle -undefined dynamic_lookup build/temp.macosx-10.13-x86_64-3.7/stdlib_asyncstreams.o build/temp.macosx-10.13-x86_64-3.7/stdlib_httpcore.o build/temp.macosx-10.13-x86_64-3.7/stdlib_os.o build/temp.macosx-10.13-x86_64-3.7/stdlib_strscans.o build/temp.macosx-10.13-x86_64-3.7/stdlib_base64.o build/temp.macosx-10.13-x86_64-3.7/stdlib_json.o build/temp.macosx-10.13-x86_64-3.7/stdlib_ospaths.o build/temp.macosx-10.13-x86_64-3.7/stdlib_strtabs.o build/temp.macosx-10.13-x86_64-3.7/nimpy_nimpy.o build/temp.macosx-10.13-x86_64-3.7/stdlib_bitops.o build/temp.macosx-10.13-x86_64-3.7/stdlib_lexbase.o build/temp.macosx-10.13-x86_64-3.7/stdlib_parsejson.o build/temp.macosx-10.13-x86_64-3.7/stdlib_strutils.o build/temp.macosx-10.13-x86_64-3.7/nimpy_py_lib.o build/temp.macosx-10.13-x86_64-3.7/stdlib_complex.o build/temp.macosx-10.13-x86_64-3.7/stdlib_lists.o build/temp.macosx-10.13-x86_64-3.7/stdlib_parseutils.o build/temp.macosx-10.13-x86_64-3.7/stdlib_system.o build/temp.macosx-10.13-x86_64-3.7/nimpy_py_types.o build/temp.macosx-10.13-x86_64-3.7/stdlib_cstrutils.o build/temp.macosx-10.13-x86_64-3.7/stdlib_macros.o build/temp.macosx-10.13-x86_64-3.7/stdlib_posix.o build/temp.macosx-10.13-x86_64-3.7/stdlib_tables.o build/temp.macosx-10.13-x86_64-3.7/nimpy_py_utils.o build/temp.macosx-10.13-x86_64-3.7/stdlib_deques.o build/temp.macosx-10.13-x86_64-3.7/stdlib_math.o build/temp.macosx-10.13-x86_64-3.7/stdlib_random.o build/temp.macosx-10.13-x86_64-3.7/stdlib_times.o build/temp.macosx-10.13-x86_64-3.7/stdlib_algorithm.o build/temp.macosx-10.13-x86_64-3.7/stdlib_dynlib.o build/temp.macosx-10.13-x86_64-3.7/stdlib_mimetypes.o build/temp.macosx-10.13-x86_64-3.7/stdlib_selectors.o build/temp.macosx-10.13-x86_64-3.7/stdlib_typetraits.o build/temp.macosx-10.13-x86_64-3.7/stdlib_asyncdispatch.o build/temp.macosx-10.13-x86_64-3.7/stdlib_epoll.o build/temp.macosx-10.13-x86_64-3.7/stdlib_nativesockets.o build/temp.macosx-10.13-x86_64-3.7/stdlib_sequtils.o build/temp.macosx-10.13-x86_64-3.7/stdlib_unicode.o build/temp.macosx-10.13-x86_64-3.7/stdlib_asyncfile.o build/temp.macosx-10.13-x86_64-3.7/stdlib_hashes.o build/temp.macosx-10.13-x86_64-3.7/stdlib_net.o build/temp.macosx-10.13-x86_64-3.7/stdlib_sets.o build/temp.macosx-10.13-x86_64-3.7/stdlib_uri.o build/temp.macosx-10.13-x86_64-3.7/stdlib_asyncfutures.o build/temp.macosx-10.13-x86_64-3.7/stdlib_heapqueue.o build/temp.macosx-10.13-x86_64-3.7/stdlib_openssl.o build/temp.macosx-10.13-x86_64-3.7/stdlib_streams.o build/temp.macosx-10.13-x86_64-3.7/stdlib_asyncnet.o build/temp.macosx-10.13-x86_64-3.7/stdlib_httpclient.o build/temp.macosx-10.13-x86_64-3.7/stdlib_options.o build/temp.macosx-10.13-x86_64-3.7/stdlib_strformat.o build/temp.macosx-10.13-x86_64-3.7/faster_than_requests_faster_than_requests.o -L/usr/local/lib -L/usr/local/opt/openssl/lib -L/usr/local/opt/sqlite/lib -o build/lib.macosx-10.13-x86_64-3.7/faster_than_requests.cpython-37m-darwin.so -flto -ffast-math -march=native -O3
  installing to build/bdist.macosx-10.13-x86_64/wheel
  running install
  running install_lib
  creating build/bdist.macosx-10.13-x86_64
  creating build/bdist.macosx-10.13-x86_64/wheel
  copying build/lib.macosx-10.13-x86_64-3.7/faster_than_requests.cpython-37m-darwin.so -> build/bdist.macosx-10.13-x86_64/wheel
  writing byte-compilation script '/var/folders/db/l41fnkcn0kjfqph_t_4mj29c0000gn/T/tmpkveswluw.py'
  /usr/local/opt/python/bin/python3.7 /var/folders/db/l41fnkcn0kjfqph_t_4mj29c0000gn/T/tmpkveswluw.py
  removing /var/folders/db/l41fnkcn0kjfqph_t_4mj29c0000gn/T/tmpkveswluw.py
  running install_egg_info
  running egg_info
  writing faster_than_requests.egg-info/PKG-INFO
  writing dependency_links to faster_than_requests.egg-info/dependency_links.txt
  writing top-level names to faster_than_requests.egg-info/top_level.txt
  warning: Failed to find the configured license file 'LICENSE'
  reading manifest file 'faster_than_requests.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  writing manifest file 'faster_than_requests.egg-info/SOURCES.txt'
  Copying faster_than_requests.egg-info to build/bdist.macosx-10.13-x86_64/wheel/faster_than_requests-0.1-py3.7.egg-info
  running install_scripts
  error: [Errno 2] No such file or directory: 'LICENSE'
  
  ----------------------------------------
  Failed building wheel for faster-than-requests
  Running setup.py clean for faster-than-requests
Failed to build faster-than-requests
Installing collected packages: faster-than-requests
  Running setup.py install for faster-than-requests ... done
Successfully installed faster-than-requests-0.1
$ python3                          
Python 3.7.3 (default, Mar 27 2019, 09:23:39) 
[Clang 10.0.0 (clang-1000.11.45.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import faster_than_requests as requests
out of memory
                                                                                                                                         
 ✘ $
```

I got this error massage after trying to install and running this module.

**Comment by juancarlospaco** [comment]
Try using GCC instead of Clang.
I think Homebrew can help, I dont use Mac tho.

**Comment by juancarlospaco** [comment]
Fixed on master.

**Comment by yxm0513** [comment]
Issue is there there with Pip install on mac

**Comment by davidthewatson** [comment]
yep, still broken on macos:

    (.venv) $ pip freeze
    faster-than-requests==0.5

    (.venv) $ python --version
    Python 3.7.4

The name is clever, but clever only counts if it works.

**Comment by Cospel** [comment]
Anyone get this to work on macos?

**Comment by friedmanchewy** [comment]
still not working on mac

**Comment by juancarlospaco** [comment]
We cant fix PIP, but check the GitHub Actions CI, 
its building everything from scratch on every push, it uses very basic bash tools (curl, git, etc):

https://github.com/juancarlospaco/faster-than-requests/commit/a422598bdebbf46018050074ff416cbb278a5df7/checks?check_suite_id=321000690

**Comment by marsch** [comment]
why is this closed? its still happening on mac - @juancarlospaco do you know an workaround ?

**Comment by juancarlospaco** [comment]
If you have problems Git clone and compile, it is a compiled module.

**Comment by maxtheman** [comment]
@juancarlospaco could you perhaps provide some example code in the readme on how to do this for mac? I see instructions for windows, but not for osx.

**Comment by juancarlospaco** [comment]
The Build is not using anything Linux-only, it uses very basic bash tools (curl, git, etc).

I do not have Mac hardware.

**Comment by marsch** [comment]
@juancarlospaco thanks - but I already tried that - and wasn't able to compile it (not with standard tools) - think its a PITA - I can't remember right now - what was it exactly 

- but i will try my very best and will share it than.

for those who want to use it on mac for now - think its best to compile it OR to use it in a docker-image

**Comment by juancarlospaco** [comment]
If you dont know what worked and what dont, 
then is impossible for me to know. 😛

Nowadays everyone is using Docker anyways, 
on any OS on any software, 
dont waste time and go with Docker
IMHO.
😉

**Comment by bsteenwi** [comment]
Mac boys:

Best option to install this:
- use brew to install nim (`brew install nim`)
- install nimpy (`nimble install nimpy`) 
- clone this repo and go to src folder
- `nim c -d:ssl -d:danger --app:lib --out:faster_than_requests.so faster_than_requests.nim`
- place the .so file in the project/code you want (or place it in your python lib folder)
- `import faster_than_requests as requests`

**Comment by juancarlospaco** [comment]
You can install stuff from PIP:

```console
$ pip install nimble_install --install-option="--nimble=nimpy"

    Downloading https://github.com/yglukhov/nimpy using git
      Verifying dependencies for nimpy@0.1.0
     Installing nimpy@0.1.0
        Prompt: nimpy@0.1.0 already exists. Overwrite? -> [forced yes]
       Success: nimpy installed successfully.

    CompletedProcess(args='nimble --accept --noColor install nimpy', returncode=0)

Successfully installed nimble-install-0.0.2

$
```
:slightly_smiling_face:
